<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\Slider\\Admin\\Admin' => $baseDir . '/includes/admin/class-admin.php',
    'AdvancedAds\\Slider\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\Slider\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\Slider\\Frontend\\Frontend' => $baseDir . '/includes/frontend/class-frontend.php',
    'AdvancedAds\\Slider\\Group_Types' => $baseDir . '/includes/class-group-types.php',
    'AdvancedAds\\Slider\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
