<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd511b7a60905090dd08c552a9ae5304f
{
    public static $classMap = array (
        'AdvancedAds\\Slider\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/admin/class-admin.php',
        'AdvancedAds\\Slider\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\Slider\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\Slider\\Frontend\\Frontend' => __DIR__ . '/../..' . '/includes/frontend/class-frontend.php',
        'AdvancedAds\\Slider\\Group_Types' => __DIR__ . '/../..' . '/includes/class-group-types.php',
        'AdvancedAds\\Slider\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitd511b7a60905090dd08c552a9ae5304f::$classMap;

        }, null, ClassLoader::class);
    }
}
